export const featureEn = {
  compact: {
    switchAccount: 'Switch viewed account', currentAccount: 'Viewing: {{account}}', noAccounts: 'No accounts',
    held: 'Reset credits held: {{count}}', applicable: '{{count}} currently usable', noApplicable: '0 currently meet the usage conditions.',
    conditions: 'Held credits and credits usable now are different counts. Availability is determined by the service.',
    nearestExpiry: 'Next expiry: {{date}}', expiredAt: 'Expiry reached: {{date}}', creditExpiry: 'Credit {{index}}: {{date}}',
    expiryUnknown: 'Expiration not provided', expiryLoading: 'Loading expiration…', expiryUnavailable: 'Expiration temporarily unavailable',
    cached: 'Showing previously fetched details', retry: 'Retry reset credit details', unsupportedPlan: 'This credit is not supported by the current plan.',
    detailsUpdated: 'Details updated {{date}}',
  },
  accountUi: {
    authIssue: 'Authentication issue', refreshIssue: 'Refresh issue',
    summary: '{{count}} accounts · {{enabled}} monitored', viewing: 'Viewing', codexFile: 'Codex login file',
    sourceTitle: 'Codex login source', sourceHint: 'Matched against the file on disk. Running sessions may retain cached credentials.',
    sourceMatched: 'Managed account matched', sourceUnmanaged: 'Account not imported', sourceMissing: 'Login file not found', sourceInvalid: 'Login file unreadable or unsupported',
    sourceUnsupported: 'Credential store: {{storage}}; file identity unavailable', sourceUnavailable: 'Login source unavailable',
    bindingChanged: 'The login file differs from the saved binding.', checked: 'Checked {{date}}', recheck: 'Recheck login file',
    details: 'Account details', editNote: 'Edit note', addNote: 'Add a note', copy: 'Copy {{label}}', copied: 'Copied', copyFailed: 'Could not copy',
    userId: 'User ID', accountId: 'Account ID', name: 'Name', provider: 'Sign-in method', managedPath: 'Managed auth.json', loginPath: 'Codex auth.json',
    tokenExpiry: 'Access token expires', subscription: 'Subscription through', daysRemaining: '{{count}} days remaining', verifySubscription: 'Needs verification',
    credentialRecord: 'Credential record', subscriptionChecked: 'Subscription checked {{date}}', subscriptionUnchecked: 'No subscription verification time supplied',
    subscriptionStart: 'Subscription started', sourceUsage: 'Latest successful usage response', sourceCredentials: 'Local credential record',
    identitySource: 'Identity source', planSource: 'Plan source', recordTime: 'Credential updated', usageTime: 'Usage updated',
    resetCredits: '{{count}} reset credits', applicableCredits: '{{count}} applicable', extraCredits: 'Extra credits', unlimited: 'Unlimited',
    available: 'Available', unavailable: 'Unavailable', availability: 'Model availability', availableAt: 'Available {{date}}',
    refreshed: 'Updated {{date}}', noRefresh: 'No successful usage refresh yet', stale: 'Last successful data', monitor: 'Monitor',
    noQuotas: 'Quota data will appear after a successful refresh.', accountFallback: 'Account {{id}}',
  },
  paused: 'Background monitoring paused',
  accounts: 'Accounts', selected: 'Viewing account', import: 'Import auth.json files', restore: 'Restore previous Codex credentials',
  empty: 'Import a Codex auth.json file to start monitoring.', note: 'Account note', save: 'Save', monitoring: 'Background monitoring',
  apply: 'Apply to Codex', remove: 'Remove credentials', bound: 'Refreshed by Codex', managed: 'Managed copy',
  expiry: 'Token expires', refreshable: 'Refresh token available', noRefresh: 'No refresh token', auth: 'Authentication',
  switchNotice: 'Exit Codex desktop, CLI and IDE sessions before applying. Reopen manually afterwards. Your provider configuration is preserved.',
  applyConfirm: 'Back up and replace the Codex login file with this account? Your custom provider will be preserved.',
  removeConfirm: 'Remove this managed credential copy? Usage history is retained.',
  applied: 'Credentials updated. Reopen Codex to use them; the model provider is unchanged.', restored: 'Previous credentials restored. Reopen Codex.',
  imported: 'Imported {{count}} file(s)', confirm: 'Confirm', cancel: 'Cancel', failed: 'Operation failed',
  model: 'Request model', auto: 'Automatic (first available text model)', refreshModels: 'Refresh model list', modelId: 'Model ID (editable)',
  modelHelp: 'Used by this account’s automatic continuation and manual test. A selected model is never silently replaced.',
  saved: 'Saved', noModels: 'Model list unavailable. You can enter a model ID and save it.',
  automaticReply: 'Latest automatic response', manualReply: 'Latest test response', legacyReply: 'This older version did not save response text.',
  noText: 'Request completed without text.', noResult: 'No request recorded.', responseModel: 'Response model', requestedModel: 'Requested model',
  uncertain: 'Delivery is uncertain. Automatic retry stopped.', truncated: 'Text was truncated.',
  rangeHint: 'Click two points to inspect a range. Arrow keys move; Enter selects; Escape clears.', clear: 'Clear selection',
  range: 'Selected range', consumed: 'Observed consumption', pp: '{{percent}} percentage points', cycles: '{{count}} cycles',
  samples: '{{count}} retained samples', duration: 'Duration', remaining: 'Remaining', used: 'Used', firstLast: 'First → last remaining',
  cycleList: 'Usage cycles', cycle: 'Cycle', reset: 'Reset', partial: 'Partial recording', outside: 'Includes data outside chart range', current: 'Current',
  exhausted: 'Observed empty {{date}}', notExhausted: 'Empty quota was not observed', detail: 'Sample details', previous: 'Previous', next: 'Next',
  retained: 'Retained observations; older data may be compacted.', precision: 'Historical buckets up to {{duration}}; exact intervals are unavailable.',
  rangePartial: 'Based on retained observations; coverage or precision is limited.',
  collecting: 'Insufficient samples', stable: 'No reliable exhaustion rate yet', lasts: 'Expected to last until reset',
  prediction: 'Est. empty {{date}} (in about {{remaining}}, {{early}} before reset)', predictionPast: 'Estimated empty time has passed; waiting for a fresh observation ({{early}} before reset)',
  early: '{{duration}} before reset',
  errors: {
    codexRunning: 'Exit all Codex desktop, CLI and IDE sessions first.', accountBound: 'This account is bound to Codex. Switch Codex to another account before removing it.',
    authStoreUnsupported: 'Codex is not confirmed to use file credentials. File switching is unavailable.', accountIdentityMissing: 'This file has no stable account identity.',
    authInvalid: 'Invalid Codex auth.json file.', authUnreadable: 'Credential file could not be read.', authenticationRequired: 'Sign in again and import fresh credentials.',
    codexRefreshRequired: 'Open Codex to refresh this bound account.', refreshTokenMissing: 'No refresh token. Import fresh credentials.',
    accountChanged: 'The Codex login file now belongs to another account. Import its latest credentials.', persistence: 'Could not save local data.',
    permissions: 'Could not restrict credential directory permissions.', network: 'Network request failed; retry later.', ready: 'Ready',
    accountMissing: 'Account no longer exists.', modelInvalid: 'Invalid model ID.', labelInvalid: 'Enter an account note of 1–120 characters.',
    processCheckFailed: 'Could not verify that Codex has exited.', switchUnsupported: 'Credential switching is currently supported on Windows.',
    accountsCorrupt: 'Account registry is unreadable; existing files have been preserved.',
  },
} as const;

export const featureZh = {
  compact: {
    switchAccount: '切换查看账号', currentAccount: '当前查看：{{account}}', noAccounts: '暂无账号',
    held: '持有重置卡 {{count}} 张', applicable: '当前可用 {{count}} 张', noApplicable: '当前满足使用条件的为 0 张。',
    conditions: '持有数量与当前可用数量不同，是否可用以服务端结果为准。',
    nearestExpiry: '最近到期：{{date}}', expiredAt: '已到期：{{date}}', creditExpiry: '第 {{index}} 张：{{date}}',
    expiryUnknown: '未返回有效期', expiryLoading: '正在查询有效期…', expiryUnavailable: '有效期暂时无法获取',
    cached: '以下为上次获取的明细', retry: '重试重置卡详情', unsupportedPlan: '当前套餐不支持这张卡。',
    detailsUpdated: '明细更新于 {{date}}',
  },
  accountUi: {
    authIssue: '认证异常', refreshIssue: '刷新异常',
    summary: '{{count}} 个账号 · {{enabled}} 个后台监测', viewing: '当前查看', codexFile: 'Codex 登录文件账号',
    sourceTitle: 'Codex 登录来源', sourceHint: '按磁盘登录文件核对，运行中的会话可能保留缓存。',
    sourceMatched: '已匹配托管账号', sourceUnmanaged: '该账号尚未导入', sourceMissing: '未找到登录文件', sourceInvalid: '登录文件无法读取或格式不支持',
    sourceUnsupported: '凭据存储：{{storage}}，无法通过文件识别账号', sourceUnavailable: '暂时无法识别登录来源',
    bindingChanged: '登录文件与保存的绑定记录不同。', checked: '检查于 {{date}}', recheck: '重新检查登录文件',
    details: '账号详情', editNote: '编辑备注', addNote: '添加备注', copy: '复制{{label}}', copied: '已复制', copyFailed: '复制失败',
    userId: '用户 ID', accountId: '账号 ID', name: '姓名', provider: '登录方式', managedPath: '托管 auth.json', loginPath: 'Codex auth.json',
    tokenExpiry: '访问令牌到期', subscription: '订阅截至', daysRemaining: '剩余 {{count}} 天', verifySubscription: '待核验',
    credentialRecord: '凭证记录', subscriptionChecked: '订阅核验于 {{date}}', subscriptionUnchecked: '凭证未提供订阅核验时间',
    subscriptionStart: '订阅开始', sourceUsage: '最近成功的用量响应', sourceCredentials: '本地凭证记录',
    identitySource: '身份来源', planSource: '套餐来源', recordTime: '凭证更新时间', usageTime: '用量更新时间',
    resetCredits: '重置卡 {{count}} 张', applicableCredits: '可使用 {{count}} 张', extraCredits: '额外额度', unlimited: '不限',
    available: '可用', unavailable: '不可用', availability: '模型可用性', availableAt: '{{date}} 可用',
    refreshed: '更新于 {{date}}', noRefresh: '尚无成功的用量刷新', stale: '上次成功数据', monitor: '监测',
    noQuotas: '成功刷新后显示额度。', accountFallback: '账号 {{id}}',
  },
  paused: '后台监测已暂停',
  accounts: '账号管理', selected: '当前查看账号', import: '导入多份 auth.json', restore: '恢复上次 Codex 凭证',
  empty: '导入 Codex auth.json 后开始监测。', note: '账号备注', save: '保存', monitoring: '后台监测',
  apply: '应用到 Codex', remove: '移除托管凭证', bound: '由 Codex 刷新令牌', managed: '托管副本',
  expiry: '令牌到期', refreshable: '可刷新令牌', noRefresh: '无刷新令牌', auth: '认证状态',
  switchNotice: '应用凭证前请退出 Codex 桌面、CLI 和 IDE 会话，完成后手动重开。保留现有 provider 配置。',
  applyConfirm: '备份并将该账号写入 Codex 登录文件？现有 custom provider 配置将保留。',
  removeConfirm: '移除此托管凭证副本？已采集的历史数据保留。',
  applied: '凭证已更新，重新打开 Codex 后生效；模型请求线路保持不变。', restored: '已恢复上次凭证，请重新打开 Codex。',
  imported: '已导入 {{count}} 份文件', confirm: '确认', cancel: '取消', failed: '操作失败',
  model: '请求模型', auto: '自动选择（首个可用文本模型）', refreshModels: '刷新模型列表', modelId: '模型 ID（可手填）',
  modelHelp: '用于此账号的自动接续和立即测试。选择模型后不会静默替换。', saved: '已保存', noModels: '模型列表暂不可用，可手填模型 ID 后保存。',
  automaticReply: '最近自动接续回复', manualReply: '最近手动测试回复', legacyReply: '旧版本未保存回复正文。',
  noText: '请求已完成，未返回文本。', noResult: '暂无请求记录。', responseModel: '响应模型', requestedModel: '请求模型',
  uncertain: '请求是否完成尚不确定，已停止自动补发。', truncated: '正文已截断。',
  rangeHint: '依次点击起点和终点查看范围。方向键移动，Enter 选点，Esc 清除。', clear: '清除选择',
  range: '选中范围', consumed: '观测消耗', pp: '{{percent}} 个百分点', cycles: '{{count}} 个周期',
  samples: '{{count}} 个留存样本', duration: '持续时间', remaining: '剩余', used: '已用', firstLast: '首末剩余',
  cycleList: '周期使用列表', cycle: '周期', reset: '重置', partial: '部分记录', outside: '包含图表范围外的数据', current: '当前周期',
  exhausted: '观测到 {{date}} 耗尽', notExhausted: '未观测到耗尽', detail: '采样明细', previous: '上一页', next: '下一页',
  retained: '展示已留存的观测数据；旧数据可能已压缩。', precision: '历史采样桶最大 {{duration}}，无法还原精确间隔。',
  rangePartial: '统计基于留存观测，覆盖范围或精度有限。',
  collecting: '样本不足', stable: '暂时没有可靠的耗尽速率', lasts: '预计可用至重置',
  prediction: '预计 {{date}} 耗尽（约 {{remaining}}后，比重置提前 {{early}}）', predictionPast: '预计耗尽时间已过，等待新观测（比重置提前 {{early}}）',
  early: '比重置提前 {{duration}}',
  errors: {
    codexRunning: '请先退出所有 Codex 桌面、CLI 和 IDE 会话。', accountBound: '此账号仍绑定 Codex，请先将 Codex 切换到其他账号再移除。',
    authStoreUnsupported: '无法确认 Codex 使用文件凭证，暂不支持文件切换。', accountIdentityMissing: '文件缺少稳定账号标识，无法托管。',
    authInvalid: 'auth.json 格式或凭证无效。', authUnreadable: '无法读取凭证文件。', authenticationRequired: '请重新登录并导入最新凭证。',
    codexRefreshRequired: '请打开 Codex 更新此绑定账号的令牌。', refreshTokenMissing: '没有 refresh_token，请导入最新凭证。',
    accountChanged: 'Codex 登录文件已变为其他账号，请导入最新凭证。', persistence: '本地数据保存失败。',
    permissions: '无法限制凭证目录的访问权限。', network: '网络请求失败，稍后重试。', ready: '可用',
    accountMissing: '账号已不存在。', modelInvalid: '模型 ID 无效。', labelInvalid: '请输入 1–120 字账号备注。',
    processCheckFailed: '无法确认 Codex 是否已经退出。', switchUnsupported: '凭证切换目前支持 Windows。',
    accountsCorrupt: '账号列表无法读取，原文件已保留。',
  },
} as const;
